import { useForm } from 'react-hook-form';
import React, { useState } from 'react';
import {
  FormErrorMessage,
  FormLabel,
  FormControl,
  Input,
  Button,
  SimpleGrid,
  Box,
  Select,
  Textarea
} from '@chakra-ui/core';
import dayjs from 'dayjs';
import './form.styles.css';

var uniqid = require('uniqid');
let currentDate = dayjs().format();

const ReportIP = () => {
  
  const { handleSubmit, errors, register } = useForm();
  const [isSubmitting, setIsSubmitting] = useState(false);

  function validateName(value) {
    let error;
    if (!value) {
      error = 'Name is required';
    } else if (value !== 'Naruto') {
      error = "Jeez! You're not a fan 😱";
    }
    return error || true;
  }

  function onSubmit(values) {
    setIsSubmitting(true);

    setTimeout(() => {
      alert(JSON.stringify(values, null, 2));
      setIsSubmitting(false);
    }, 1000);
  }

  
  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <FormControl isInvalid={errors.name}>
        <SimpleGrid
          id="mainGrid"
          minChildWidth="315px"
          spacing={10}
          columns={2}
          bg="white"
        >
          <Box minWidth="3rem">
            <FormLabel htmlFor="name">Autogenerated Fields</FormLabel>
            <SimpleGrid width="100%" columns={2}>
              <Input
                isDisabled
                name="currentDate"
                placeholder="Time/Date"
                value={currentDate}
              />

              <Input
                isDisabled
                marginLeft="5px"
                name="id"
                placeholder="Incident ID"
                value={uniqid()}
              />
            </SimpleGrid>
          </Box>
          <Box minWidth="3rem">
            <FormLabel htmlFor="lol">Name of Ship</FormLabel>
            <Select name="shipName" ref={register}>
              <option value="0" isDisabled>
                Please select...
              </option>
              <option value="ScarletLady">Scarlet Lady</option>
              <option value="DeathStar">Death Star</option>
            </Select>
          </Box>
          <Box minWidth="3rem">
            <FormLabel htmlFor="name">
              Date and Time this injury happened
            </FormLabel>
            <SimpleGrid width="100%" columns={2}>
              <Input
                type="date"
                name="name"
                placeholder="name"
                ref={register({ validate: validateName })}
              />

              <Input
                marginLeft="5px"
                type="time"
                name="name"
                placeholder="name"
                ref={register({ validate: validateName })}
              />
            </SimpleGrid>
          </Box>
          <Box>
            <FormLabel htmlFor="name">
              Date and Time this injury was reported
            </FormLabel>
            <SimpleGrid width="100%" columns={2}>
              <Input
                type="date"
                name="name"
                placeholder="name"
                ref={register({ validate: validateName })}
              />

              <Input
                marginLeft="5px"
                type="time"
                name="name"
                placeholder="name"
                ref={register({ validate: validateName })}
              />
            </SimpleGrid>
          </Box>
          <Box minWidth="3rem">
            <FormLabel htmlFor="name">Injury first reported by</FormLabel>
            <Select name="shipName" ref={register}>
              <option value="0" isDisabled>
                Please select...
              </option>
              <option value="Crew">Crew</option>
              <option value="Passenger">Passenger</option>
              <option value="Vendor">Vendor</option>
            </Select>
          </Box>
          <Box minWidth="3rem">
            <FormLabel htmlFor="name">Person completing this report:</FormLabel>
            <SimpleGrid width="100%" columns={3}>
              <Input
                name="name"
                placeholder="first name"
                ref={register({ validate: validateName })}
              />
              <Input
                marginLeft="5px"
                name="name"
                placeholder="last name"
                ref={register({ validate: validateName })}
              />
              <Input
                marginLeft="10px"
                name="name"
                placeholder="position"
                ref={register({ validate: validateName })}
              />
            </SimpleGrid>
          </Box>
          <Box minWidth="3rem">
            <FormLabel htmlFor="name">Personal Injury Category</FormLabel>
            <Select name="shipName" ref={register}>
              <option value="0" isDisabled>
                Please select...
              </option>
              <option value="Crew">Passenger</option>
              <option value="Passenger">Crew</option>
              <option value="Vendor">Other</option>
            </Select>
          </Box>
          <Box minWidth="3rem">
            <FormLabel htmlFor="name">Personal Injury Category</FormLabel>
            <Select name="shipName" ref={register}>
              <option value="0" isDisabled>
                Please select...
              </option>
              <option value="Public Pax Area">Public Pax Area</option>
              <option value="Crew Area">Crew Area</option>
              <option value="Pax \ Crew Cabin">Pax \ Crew Cabin</option>
              <option value=" Ashore">Ashore</option>
              <option value="Other">Other</option>
            </Select>
          </Box>
          <Box minWidth="3rem">
            <FormLabel htmlFor="name">Level of Incident</FormLabel>
            <Select name="shipName" ref={register}>
              <option value="0" isDisabled>
                Please select...
              </option>
              <option value="Minor">Minor</option>
              <option value="Moderate">Moderate</option>
              <option value="Serious">Serious</option>
            </Select>
          </Box>
          <Box minWidth="3rem">
            <FormLabel htmlFor="name">Specific Incident Location</FormLabel>
            <Input
              name="specificLocation"
              placeholder="eg. Shower inside crew cabin 23341"
            />
          </Box>
          <Box minWidth="3rem">
            <FormLabel htmlFor="name">
              Did the incident involve any Equipment
            </FormLabel>
            <Select name="shipName" ref={register}>
              <option value="0" isDisabled>
                Please select...
              </option>
              <option value="Yes">Yes</option>
              <option value="No">No</option>
            </Select>
          </Box>
          <Box minWidth="3rem">
            <FormLabel htmlFor="name">
              Condition of the Equipment involved
            </FormLabel>
            <Textarea placeholder="Describe current state of equipment" />
          </Box>
          <Box minWidth="3rem">
            <FormLabel htmlFor="name">
              Does this equipment require regular inspection?
            </FormLabel>
            <Select name="shipName" ref={register}>
              <option value="0" isDisabled>
                Please select...
              </option>
              <option value="Yes">Yes</option>
              <option value="No">No</option>
            </Select>
          </Box>
          <Box minWidth="3rem">
            <FormLabel htmlFor="name">
              Person in charge of this inspetion
            </FormLabel>
            <SimpleGrid width="100%" columns={2}>
              <Input
                name="name"
                placeholder="name"
                ref={register({ validate: validateName })}
              />
              <Input
                marginLeft="5px"
                name="name"
                placeholder="position"
                ref={register({ validate: validateName })}
              />
            </SimpleGrid>
          </Box>
          <Box>
            <FormLabel htmlFor="name">Date of last inspection</FormLabel>
            <Input
              type="date"
              marginLeft="5px"
              name="inspectionDate"
              placeholder="position"
            />
          </Box>
          <Box minWidth="3rem">
            <FormLabel htmlFor="name">
              Does this equipment require regular maintenance?
            </FormLabel>
            <Select name="shipName" ref={register}>
              <option value="0" isDisabled>
                Please select...
              </option>
              <option value="Yes">Yes</option>
              <option value="No">No</option>
            </Select>
          </Box>
          <Box minWidth="3rem">
            <FormLabel htmlFor="name">
              Person in charge of Maintenance:
            </FormLabel>
            <SimpleGrid width="100%" columns={3}>
              <Input
                name="name"
                placeholder="first name"
                ref={register({ validate: validateName })}
              />
              <Input
                marginLeft="5px"
                name="name"
                placeholder="last name"
                ref={register({ validate: validateName })}
              />
              <Input
                marginLeft="10px"
                name="name"
                placeholder="position"
                ref={register({ validate: validateName })}
              />
            </SimpleGrid>
          </Box>
          <Box>
            <FormLabel htmlFor="name">
              Date maintenance was last performed:
            </FormLabel>
            <Input
              type="date"
              marginLeft="5px"
              name="inspectionDate"
              placeholder="position"
            />
          </Box>
          <Box minWidth="3rem">
            <FormLabel htmlFor="name">
              Did the incident involve any alcohol\drugs
            </FormLabel>
            <Select name="shipName" ref={register}>
              <option value="0" isDisabled>
                Please select...
              </option>
              <option value="Yes">Yes</option>
              <option value="No">No</option>
            </Select>
          </Box>
          <Box minWidth="3rem">
            <FormLabel htmlFor="name">Deck Surface</FormLabel>
            <Select name="shipName" ref={register}>
              <option value="0" isDisabled>
                Please select...
              </option>
              <option value="Metal">Metal</option>
              <option value="Wood">Wood</option>
              <option value="Carpet">Carpet</option>
              <option value="Marble">Marble</option>
              <option value="Stone">Stone</option>
              <option value="Concrete">Concrete</option>
              <option value="Other">Other</option>
            </Select>
          </Box>
          <Box minWidth="3rem">
            <FormLabel htmlFor="name">Conditions of the Deck</FormLabel>
            <Select name="shipName" ref={register}>
              <option value="0" isDisabled>
                Please select...
              </option>
              <option value="Dry">Dry</option>
              <option value="Wet">Wet</option>
              <option value="Other">Other</option>
            </Select>
          </Box>
          <Box minWidth="3rem">
            <FormLabel htmlFor="name">
              Person in charge of the incident location:
            </FormLabel>
            <SimpleGrid width="100%" columns={3}>
              <Input
                name="name"
                placeholder="first name"
                ref={register({ validate: validateName })}
              />
              <Input
                marginLeft="5px"
                name="name"
                placeholder="last name"
                ref={register({ validate: validateName })}
              />
              <Input
                marginLeft="10px"
                name="name"
                placeholder="position"
                ref={register({ validate: validateName })}
              />
            </SimpleGrid>
          </Box>
          <Box minWidth="3rem">
            <FormLabel htmlFor="name">Ship Location</FormLabel>
            <Select name="shipName" ref={register}>
              <option value="0" isDisabled>
                Please select...
              </option>
              <option value="At sea">At sea</option>
              <option value="In port">In port</option>
            </Select>
          </Box>
          <Box>
            <FormLabel htmlFor="name">
              Sea Conditions at the time of incident:
            </FormLabel>
            <Input
              marginLeft="5px"
              name="inspectionDate"
              placeholder="position"
            />
          </Box>
          <Box minWidth="3rem">
            <FormLabel htmlFor="name">
              Stabilizers operating at time of incident
            </FormLabel>
            <Select name="shipName" ref={register}>
              <option value="0" isDisabled>
                Please select...
              </option>
              <option value="Yes">Yes</option>
              <option value="No">No</option>
            </Select>
          </Box>
          <Box>
            <FormLabel htmlFor="name">
              Weather at the time of incident:
            </FormLabel>
            <Input name="inspectionDate" placeholder="position" />
          </Box>
          <Box>
            <FormLabel htmlFor="name">Incident Description:</FormLabel>
            <Textarea placeholder="Describe the incident" />
          </Box>
        </SimpleGrid>
      </FormControl>
      <Button
        mt={4}
        variantColor="teal"
        isLoading={isSubmitting}
        type="submit"
        margin="1rem auto"
        width="6rem"
      >
        Submit
      </Button>
    </form>
  );
}
  

export default ReportIP;

import React, { Component } from 'react';

export default class FormDataComponent extends Component {

    userData;

    constructor(props) {
        super(props);

        this.onChangeName = this.onChangeName.bind(this);
        this.onChangeEmail = this.onChangeEmail.bind(this);
        this.onChangePhone = this.onChangePhone.bind(this);
        this.onSubmit = this.onSubmit.bind(this);

        this.state = {
            name: '',
            email: '',
            phone: ''
        }
    }

    // Form Events
    onChangeName(e) {
        this.setState({ name: e.target.value })
    }

    onChangeEmail(e) {
        this.setState({ email: e.target.value })
    }

    onChangePhone(e) {
        this.setState({ phone: e.target.value })
    }

    onSubmit(e) {
        e.preventDefault()

        this.setState({
            name: '',
            email: '',
            phone: ''
        })
    }

    // React Life Cycle
    componentDidMount() {
        this.userData = JSON.parse(localStorage.getItem('user'));

        if (localStorage.getItem('user')) {
            this.setState({
                name: this.userData.name,
                email: this.userData.email,
                phone: this.userData.phone
            })
        } else {
            this.setState({
                name: '',
                email: '',
                phone: ''
            })
        }
    }

    componentWillUpdate(nextProps, nextState) {
        localStorage.setItem('user', JSON.stringify(nextState));
    }


    render() {
        return (
            <div className="container">
                <form onSubmit={this.onSubmit}>
                    <div className="form-group">
                        <label>Name</label>
                        <input type="text" className="form-control" value={this.state.name} onChange={this.onChangeName} />
                    </div>
                    <div className="form-group">
                        <label>Email</label>
                        <input type="email" className="form-control" value={this.state.email} onChange={this.onChangeEmail} />
                    </div>
                    <div className="form-group">
                        <label>Phone</label>
                        <input type="tel" className="form-control" value={this.state.phone} onChange={this.onChangePhone} />
                    </div>
                    <button type="submit" className="btn btn-primary btn-block">Submit</button>
                </form>
            </div>
        )
    }
}